---
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Copy default.conf file of NGINX
      copy:
        src: files/default
        dest: /etc/nginx/sites-enabled/
        mode: preserve