---
    - name: Update the software package repository
      become: true
      apt:
        update_cache: yes

    - name: Install Consul
      become: true
      apt:
        name: consul
        state: present
      
    #- name: Install consul-template
    #  become: true
    #  command: >
    #    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
    #  when: inventory_hostname == 'lb01'
    - name: Install python3-apt
      become: true
      apt:
        name: python3-apt
        state: present
      when: inventory_hostname == 'lb01'

    - name: Download HashiCorp GPG key
      become: true
      shell: 
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
      when: inventory_hostname == 'lb01'

    - name: Add hashicorp repo to systems resources
      become: true
      shell:
        echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      when: inventory_hostname == 'lb01'
    
    - name: Update package cache
      become: true
      apt:
        update_cache: yes
      when: inventory_hostname == 'lb01'
      
    - name: Install consul-template
      become: true
      shell:
        sudo apt-get install consul-template
      when: inventory_hostname == 'lb01'

    - name: Create directories for Consul
      file:
        path: /var/lib/consul
        state: directory
        owner: consul
        group: consul
        mode: '0775'
        recurse: yes
    
    - name: Create /etc/consul.d directory
      file:
        path: /etc/consul.d
        state: directory
        owner: consul
        group: consul

    - name: Create templates directory for load-balancing service
      become: true
      file:
        path: /etc/templates
        state: directory
        mode: "0755"
      when: inventory_hostname == 'lb01'

    - name: Copy load-balancing template file
      become: true
      copy:
        src: files/load-balancer.conf.ctmpl
        dest: /etc/templates/
      when: inventory_hostname == 'lb01'

    - name: Copy consul.service file
      template:
        src: files/consul.service.j2
        dest: /etc/systemd/system/consul.service
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname != 'consul'

    - name: Copy config.json file
      template:
        src: files/config.json.j2
        dest: /etc/consul.d/config.json
        owner: consul
        group: consul
        mode: '0644'
      when: inventory_hostname != 'consul'

    - name: Copy consul.service file
      template:
        src: files/consul.service
        dest: /etc/systemd/system/consul.service
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == 'consul'
    
    - name: Copy config.json file
      template:
        src: files/config.json
        dest: /etc/consul.d/config.json
        owner: consul
        group: consul
        mode: '0644'
      when: inventory_hostname == 'consul'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Consul service
      service:
        name: consul
        state: started
        enabled: yes

    - name: Check if Consul service is active
      command: systemctl is-active --quiet consul
      register: consul_active
      changed_when: false

    - name: Display Consul service status
      debug:
        msg: "Consul service is {{ 'active' if consul_active.rc == 0 else 'inactive' }}"