---
    - name: Update the software package repository
      apt:
        update_cache: yes

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - curl
        - net-tools
        - unzip

    - name: Install consul
      unarchive:
        src: https://releases.hashicorp.com/consul/1.1.0/consul_1.1.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: Verify consul installation
      shell: "consul --version"
      register: consul_version

    - assert:
        that:
          - "'Consul' in consul_version.stdout"

    - name: Create consul user
      user:
        name: consul

    - name: Create Consul /var directory
      file:
        path: /var/consul
        state: directory
        owner: consul
        group: consul
        mode: 0755

    - name: Copy Consul configuration
      copy:
        src: files/consul.hcl
        dest: /etc/consul.d/consul.hcl
        mode: "0644"
    
    - name: Copy Consul systemd service file
      copy:
        src: files/consul.service
        dest: /etc/systemd/system/consul.service
        mode: "0644"

    - name: Copy server.hcl file
      become: true
      copy:
        src: files/server.hcl
        dest: /etc/consul.d/server.hcl
        owner: consul
        group: consul
        mode: "0640"

    - name: Enable and start Consul service
      systemd:
        name: consul
        state: started
        enabled: true

    - name: Create Consul bootstrap directory
      file:
        path: /etc/consul.d/bootstrap
        state: directory
        mode: '0755'

    - name: Copy configuration file
      copy:
        src: /files/bootstrap-config.json
        dest: /etc/consul.d/bootstrap/config.json

    - name: Copy systemd bootstrap consul.service
      copy:
        src: /files/bootstrap-consul.service
        dest: /etc/systemd/system/consul.service

    - name: Start bootstrap Consul
      systemd:
        name: consul.service
        state: started


